version: '3.8'

services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - FIREWALL=1
    volumes:
      - ~/ovpn/Netherland.ovpn:/vpn/config.ovpn 
    networks:
      - vpn_network
    restart: unless-stopped

  app:
    image: nimeapi-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8020
    environment:
      - NODE_ENV=production
    networks:
      - vpn_network
    depends_on:
      - vpn
    ports:
      - "8020:8020"
    restart: unless-stopped

networks:
  vpn_network:
    driver: bridge