services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - FIREWALL=1
    volumes:
      - /home/deployuser/ovpn/Netherland.ovpn:/vpn/config.ovpn
      - /home/deployuser/ovpn/apass.txt:/vpn/apass.txt
    networks:
      - vpn_network
    ports:
          - "8020:8020"
    restart: unless-stopped

  app:
    image: nimeapi-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8020
    environment:
      - NODE_ENV=production
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: unless-stopped

networks:
  vpn_network:
    driver: bridge
